server:
  servlet:
    context-path: /produdoro/api

spring:
  data:
    mongodb:
      authentication-database: admin
      uri: ${MONGO_DB_URI:mongodb+srv://devmathiasx:OOEJkevofL2flYXB@wakanda.ilfwhj2.mongodb.net/wakanda?retryWrites=true&w=majority}
      auto-index-creation: true